import { SampleBrochure } from "./types";

export const SAMPLE_BROCHURES: SampleBrochure[] = [
  {
    id: "sample-1",
    title: "AEON BiG House Brand Fair Cover",
    dateRange: "9 April - 6 May 2026",
    imageUrl: "https://i.imgur.com/KzS63fT.jpg", // AEON BiG cover image or fallback
    retailer: "AEON BiG",
    theme: "House Brand Fair",
    category: "Household & Food Cover",
    records: [
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "House Brand Fair",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - House Brand Fair",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-05-06",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-1",
        "Feature Type": "Price_Off",
        "Product Name": "Topvalu Bestprice Colour Care Liquid Laundry Detergent 1.8kg",
        "Brand ID": "BR-TV-01",
        Department: "Household",
        "Brand Name": "Topvalu Bestprice",
        "Brand Type": "Housebrand",
        Category: "Detergent",
        Subcategory: "Liquid Detergent",
        "Subcategory ID": "sub-det-01",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 12.50,
        "Promo Price": 9.90,
        "Promo Price (Upper Range)": "",
        "Discount %": 20.8,
        "No of Pack": 1,
        Size: "1.8kg",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 9.90,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_cover.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      },
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "House Brand Fair",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - House Brand Fair",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-05-06",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-2",
        "Feature Type": "Price_Off",
        "Product Name": "BIG Value Colour Care Liquid Laundry Detergent 3kg",
        "Brand ID": "BR-BV-02",
        Department: "Household",
        "Brand Name": "BIG Value",
        "Brand Type": "Housebrand",
        Category: "Detergent",
        Subcategory: "Liquid Detergent",
        "Subcategory ID": "sub-det-01",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": "",
        "Promo Price": 10.90,
        "Promo Price (Upper Range)": "",
        "Discount %": "",
        "No of Pack": 1,
        Size: "3kg",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 10.90,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_cover.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      },
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "House Brand Fair",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - House Brand Fair",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-05-06",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-3",
        "Feature Type": "Price_Off",
        "Product Name": "Sega2go Organic Apples (pack of 5)",
        "Brand ID": "BR-SG-03",
        Department: "Fresh",
        "Brand Name": "Sega2go",
        "Brand Type": "Branded",
        Category: "Fruit",
        Subcategory: "Apple",
        "Subcategory ID": "sub-fru-01",
        "Supplier Name": "Sega Food Products",
        "Supplier ID": "SUP-SEGA",
        "Original Price": 9.50,
        "Promo Price": 7.90,
        "Promo Price (Upper Range)": "",
        "Discount %": 16.8,
        "No of Pack": 5,
        Size: "5s",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "No",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 1.58,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_cover.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      }
    ]
  },
  {
    id: "sample-2",
    title: "Page 2: Topvalu Spreads & Peanut Butter",
    dateRange: "9 - 22 April 2026",
    imageUrl: "https://i.imgur.com/boflV9e.jpg", // actual image url
    retailer: "AEON BiG",
    theme: "Your Life Your Brand",
    category: "Groceries & Spreads",
    records: [
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-4",
        "Feature Type": "Price_Off",
        "Product Name": "Peanut Butter Creamy / Crunchy 500G",
        "Brand ID": "BR-TV-01",
        Department: "Grocery",
        "Brand Name": "Topvalu",
        "Brand Type": "Housebrand",
        Category: "Jam & Spread",
        Subcategory: "Peanut Butter",
        "Subcategory ID": "sub-spr-02",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 16.50,
        "Promo Price": 14.90,
        "Promo Price (Upper Range)": "",
        "Discount %": 9.7,
        "No of Pack": 1,
        Size: "500G",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "Creamy or Crunchy variety available",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 14.90,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_spreads.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      },
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-5",
        "Feature Type": "Price_Off",
        "Product Name": "Caramelized Biscuit Spread 350G",
        "Brand ID": "BR-TV-01",
        Department: "Grocery",
        "Brand Name": "Topvalu",
        "Brand Type": "Housebrand",
        Category: "Jam & Spread",
        Subcategory: "Biscuit Spread",
        "Subcategory ID": "sub-spr-03",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 15.00,
        "Promo Price": 12.90,
        "Promo Price (Upper Range)": "",
        "Discount %": 14.0,
        "No of Pack": 1,
        Size: "350G",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 12.90,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_spreads.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      },
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-6",
        "Feature Type": "Price_Off",
        "Product Name": "Pistachio & Hazelnut with Cocoa Spread 200G",
        "Brand ID": "BR-TV-01",
        Department: "Grocery",
        "Brand Name": "Topvalu",
        "Brand Type": "Housebrand",
        Category: "Jam & Spread",
        Subcategory: "Hazelnut Spread",
        "Subcategory ID": "sub-spr-04",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 22.00,
        "Promo Price": 18.90,
        "Promo Price (Upper Range)": "",
        "Discount %": 14.1,
        "No of Pack": 1,
        Size: "200G",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 18.90,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_spreads.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      },
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-7",
        "Feature Type": "Price_Off",
        "Product Name": "Hazelnut Cocoa Spread 350G",
        "Brand ID": "BR-TV-01",
        Department: "Grocery",
        "Brand Name": "Topvalu",
        "Brand Type": "Housebrand",
        Category: "Jam & Spread",
        Subcategory: "Hazelnut Spread",
        "Subcategory ID": "sub-spr-04",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 15.00,
        "Promo Price": 12.90,
        "Promo Price (Upper Range)": "",
        "Discount %": 14.0,
        "No of Pack": 1,
        Size: "350G",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 12.90,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_spreads.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      }
    ]
  },
  {
    id: "sample-3",
    title: "Page 3: Topvalu Frozen Chicken Nuggets & Seafood",
    dateRange: "9 - 22 April 2026",
    imageUrl: "https://i.imgur.com/gU8bNve.jpg", // actual image url
    retailer: "AEON BiG",
    theme: "Your Life Your Brand",
    category: "Chilled & Frozen Foods",
    records: [
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-8",
        "Feature Type": "Price_Off",
        "Product Name": "Chicken Cocktail Original / Cheese 500G",
        "Brand ID": "BR-TV-01",
        Department: "Chilled & Frozen",
        "Brand Name": "Topvalu",
        "Brand Type": "Housebrand",
        Category: "Frozen Meat",
        Subcategory: "Chicken Sausage",
        "Subcategory ID": "sub-fzn-01",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 11.50,
        "Promo Price": 9.00,
        "Promo Price (Upper Range)": "",
        "Discount %": 21.7,
        "No of Pack": 1,
        Size: "500G",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "Available in Original or Cheese flavors",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 9.00,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_frozen.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      },
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-9",
        "Feature Type": "Price_Off",
        "Product Name": "Tempura Chicken Nuggets Original 750G",
        "Brand ID": "BR-TV-01",
        Department: "Chilled & Frozen",
        "Brand Name": "Topvalu",
        "Brand Type": "Housebrand",
        Category: "Frozen Meat",
        Subcategory: "Chicken Nuggets",
        "Subcategory ID": "sub-fzn-02",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 17.90,
        "Promo Price": 14.90,
        "Promo Price (Upper Range)": "",
        "Discount %": 16.8,
        "No of Pack": 1,
        Size: "750G",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 14.90,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_frozen.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      },
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-10",
        "Feature Type": "Price_Off",
        "Product Name": "Breaded Chicken Nuggets 1KG",
        "Brand ID": "BR-TV-01",
        Department: "Chilled & Frozen",
        "Brand Name": "Topvalu",
        "Brand Type": "Housebrand",
        Category: "Frozen Meat",
        Subcategory: "Chicken Nuggets",
        "Subcategory ID": "sub-fzn-02",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 19.90,
        "Promo Price": 16.90,
        "Promo Price (Upper Range)": "",
        "Discount %": 15.1,
        "No of Pack": 1,
        Size: "1KG",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 16.90,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_frozen.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      },
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-11",
        "Feature Type": "Price_Off",
        "Product Name": "Chicken Frankfurter 340G",
        "Brand ID": "BR-TV-01",
        Department: "Chilled & Frozen",
        "Brand Name": "Topvalu",
        "Brand Type": "Housebrand",
        Category: "Frozen Meat",
        Subcategory: "Chicken Sausage",
        "Subcategory ID": "sub-fzn-01",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 5.20,
        "Promo Price": 4.50,
        "Promo Price (Upper Range)": "",
        "Discount %": 13.5,
        "No of Pack": 1,
        Size: "340G",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "SPD",
        "Premium Description": "Special Offer: Buy 3 @ RM12.90",
        "Special Premium": "Yes",
        "Signficant Promotion": "Multi Purchase Gift (MPG)",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 4.30,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_frozen.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      }
    ]
  },
  {
    id: "sample-4",
    title: "Page 4: Topvalu Beverages, Nuts, Chips",
    dateRange: "9 - 22 April 2026",
    imageUrl: "https://i.imgur.com/N6EAt5S.jpg", // actual image url
    retailer: "AEON BiG",
    theme: "Your Life Your Brand",
    category: "Beverages & Snacks",
    records: [
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-12",
        "Feature Type": "Range Premium",
        "Product Name": "Malt Chocolate Drink 400G - 900G",
        "Brand ID": "BR-TV-01",
        Department: "Grocery",
        "Brand Name": "Topvalu",
        "Brand Type": "Housebrand",
        Category: "Beverage",
        Subcategory: "Chocolate Malt",
        "Subcategory ID": "sub-bev-01",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": "",
        "Promo Price": 7.50,
        "Promo Price (Upper Range)": 16.90,
        "Discount %": "",
        "No of Pack": 1,
        Size: "400G-900G",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "Price ranges from RM7.50 to RM16.90 depending on pack size",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": 7.50,
        "Discount To": 16.90,
        "Price Per Pack": "",
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_beverages.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      },
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-13",
        "Feature Type": "Price_Off",
        "Product Name": "Dried Mango 200G",
        "Brand ID": "BR-TV-02",
        Department: "Grocery",
        "Brand Name": "Topvalu Bestprice",
        "Brand Type": "Housebrand",
        Category: "Snacks",
        Subcategory: "Dried Fruits",
        "Subcategory ID": "sub-snk-01",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 17.50,
        "Promo Price": 15.00,
        "Promo Price (Upper Range)": "",
        "Discount %": 14.3,
        "No of Pack": 1,
        Size: "200G",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 15.00,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_beverages.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      },
      {
        Country: "MY",
        Currency: "MYR",
        "Mailer ID": "M-2026-AB1",
        "Source Type": "Mailer",
        "Publication Date": "2026-04-09",
        "Retailer ID": "RET-AB01",
        "Retailer Banner": "AEON BiG",
        "Retailer Chain Group": "AEON Group",
        "Channel Type": "Hypermarket",
        "Region ID": "REG-WM",
        "Region Name": "West Malaysia",
        Theme: "Your Life Your Brand",
        "Theme Category": "House Brand Promotion",
        "Significant Thematic": "AEON BiG - Your Life Your Brand",
        "Significant Thematic Special": "Yes",
        "Promotion Start Date": "2026-04-09",
        "Promotion End Date": "2026-04-22",
        Town: "",
        "Outlet Opening": "No",
        "Feature ID": "FEAT-14",
        "Feature Type": "Price_Off",
        "Product Name": "Roasted Nuts / Salted Pistachios / Cashews / Almonds / Mixed Nuts 130G - 150G",
        "Brand ID": "BR-TV-01",
        Department: "Grocery",
        "Brand Name": "Topvalu",
        "Brand Type": "Housebrand",
        Category: "Snacks",
        Subcategory: "Nuts",
        "Subcategory ID": "sub-snk-02",
        "Supplier Name": "AEON Co. (M) Bhd",
        "Supplier ID": "SUP-AEON",
        "Original Price": 14.50,
        "Promo Price": 12.90,
        "Promo Price (Upper Range)": "",
        "Discount %": 11.0,
        "No of Pack": 1,
        Size: "130G-150G",
        "Limited Buy": "No",
        "No of Limited Buy": "",
        "Activity Name": "",
        "Promo Mechanic": "PO",
        "Premium Description": "Types: Salted Pistachios, Cashews, Roasted Almond, Mixed Nuts & Fruits",
        "Special Premium": "No",
        "Signficant Promotion": "No",
        "PWP Value": "",
        "Member Price Value": "",
        "New SKU? New Packaging? New Pack Size": "No",
        Exclusivity: "Yes",
        "Discount From": "",
        "Discount To": "",
        "Price Per Pack": 12.90,
        Year: 2026,
        Month: 4,
        Week: 15,
        Quarter: "Q2",
        YTD: "YTD TY",
        MAT: "MAT TY",
        sourceImageName: "aeon_big_beverages.jpg",
        extractedAt: "2026-05-21T03:35:08Z"
      }
    ]
  }
];
